- name: Various Tasks
  hosts: "{{ switch_name }}"
  gather_facts: yes
  become: yes
  become_method: enable

  tasks:

    # Modify Port Parameters for ios device from values entered in Tower Survey
    - name: Configure Switch Port(s)
      block:
        - name: Modify Cisco Switch Port
          ios_config:
            src: "templates/pr_ios_portconfig.j2"
            save_when: modified
          when: ansible_facts.net_system == "ios"
