---

- name: Various Tasks
  hosts: "{{ switch_name }}"
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

    - name: Configure port
      eos_config:
        lines:
        - description Customer/Voice
        - switchport trunk native vlan {{ access_vlanID }}
        - switchport mode trunk
        - spanning-tree portfast
        - no shutdown
        parents: interface {{ interface_name }}

    # - name: Set Hostname
    #   eos_config:
    #     lines: hostname {{ inventory_hostname }}
    #     save_when: always

    - name: run multiple commands on remote nodes
      eos_command:
        commands:
        - show version
        - show interfaces
        wait_for:
        - result[0] contains vEOS
        - result[1] contains Loopback0