---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Various Tasks
  hosts: "{{ switch_name }}"
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

    # - name: Configure Port
    #   eos_config:
    #     lines:
    #     # - switchport trunk native vlan {{ access_vlanID }}
    #     - switchport mode trunk
    #     - spanning-tree portfast
    #     # - no shutdown
    #     parents: interface {{ interface_name }}

    # Modify Port Description if value entered in Tower Survey
    - name: Modify Port Description
      eos_config:
        lines:
        - description {{ port_desc }}
        parents: interface {{ interface_name }}
      when: port_desc != ""

    # Modify Port Access VLAN ID if value entered in Tower Survey
    - name: Modify Access VLAN ID
      eos_config:
        lines:
        - switchport trunk native vlan {{ access_vlanID }}
        - switchport mode trunk
        - spanning-tree portfast
        parents: interface {{ interface_name }}
      when: access_vlanID != ""

    # Modify Port Speed if value entered in Tower Survey
    - name: Modify Port Speed
      eos_config:
        lines:
        - speed {{ port_speed }}
        parents: interface {{ interface_name }}
      when: port_speed != ""