---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Various Tasks
  hosts: "{{ switch_name }}"
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

    - name: Configure Port
      eos_config:
        lines:
        - switchport trunk native vlan {{ access_vlanID }}
        - switchport mode trunk
        - spanning-tree portfast
        - no shutdown
        - default speed
        parents: interface {{ interface_name }}

    # Change Port Description if value entered in Tower Survey
    - name: Configure Port Description
      eos_config:
        lines:
        - description {{ port_desc }}
        parents: interface {{ interface_name }}
      when: port_desc