---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Retrieve running config of {{ interface_names | join(',') }} on "{{ switch_name }}"
  hosts: "{{ switch_name }}"
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

  # Show Port's current running-config
    - name: Gather {{ interface_names | join(',') }} running-config
      eos_command:
        commands:
          - show running-config interfaces {{ interface_names | join(',') }}
      register: interface_config

    - name: Display Current running-config of {{ interface_names | join(',') }}
      debug:
        msg: "{{ interface_config.stdout_lines[0] }}"