---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Show running config of interface
  hosts: "{{ switch_name }}"
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

  # Show Port's current running-config
    - name: Gather port running-config
      eos_command:
        commands:
          - show running-config interfaces {{ interface_name }}
      register: interface_config

    - name: Display Result
      debug:
        msg: "{{ interface_config.stdout_lines[0] }}"