---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Various Tasks
  hosts: "{{ switch_name }}"
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

  # Show Port's current running-config
    - name: run show version on remote devices
      eos_command:
        commands: show run interface {{ interface_name }}