---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Show running config of interface
  hosts: veos1
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

  # Show Port's current running-config
    - name: Show port running-config
      eos_command:
        commands:
          - configure
          - interface Ethernet1
          - show active
        authorize: yes