---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Various Tasks
  hosts: localhost
  gather_facts: no
  become: yes
  become_method: enable

  vars:
    interfaces:
      - Ethernet8
      - Ethernet9

  tasks:

    # Change Port Description if value entered in Tower Survey
    - name: Configure Port Description
      debug:
        # msg: "{{ interfaces | join(',') }}"
        msg:
          - "{{ interfaces[0] }}"
          - "{{ interfaces | join(',') }}"
