---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Various Tasks
  hosts: veos1
  gather_facts: no
  become: yes
  become_method: enable

  vars:
    port_desc: ""

  tasks:

    - name: Configure Port
      eos_config:
        lines:
        - switchport trunk native vlan 200
        - switchport mode trunk
        - spanning-tree portfast
        - no shutdown
        - default speed
        parents: interface Ethernet1

    # Change Port Description if value entered in Tower Survey
    - name: Configure Port Description
      eos_config:
        lines:
        - description {{ port_desc }}
        parents: interface Ethernet1
      when: port_desc != ""