---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Various Tasks
  hosts: poe-sw1
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

    # - name: Gather all legacy facts
    #   eos_facts:
    #     gather_subset: all
    #   register: switch_vars

    - name: Get Checkpoints
      eos_command:
        commands:
          - show configuration checkpoints
      register: checkpoints

    # Debug: Print the variables
    - name: Print out the variables
      debug:
        msg: "{{ checkpoints['stdout'][0].split('\n')[-1].split()[0] }}"