---

# Playbook executed in Tower with a Survey to gather inputs below

- name: Various Tasks
  hosts: poe-sw1, poe-sw2
  gather_facts: yes
  become: yes
  become_method: enable

  tasks:

    - name: Print all available facts
      debug:
        #var: ansible_facts
        msg: "{{ ansible_facts.net_hostname }} is running {{ ansible_facts.net_system }} version {{ ansible_facts.net_version }}"